name: Jekyll site CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site with Jekyll (Docker)
        run: |
          docker run --rm             -v ${{ github.workspace }}:/srv/jekyll             -v ${{ github.workspace }}/_site:/srv/jekyll/_site             jekyll/builder:latest             /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Upload _site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          force_orphan: true